apiVersion: cloud-build-notifiers/v1
kind: SlackNotifier
metadata:
  name: cloudbuild-slack-notifier
spec:
  notification:
    filter: build.status in [Build.Status.SUCCESS, Build.Status.FAILURE, Build.Status.TIMEOUT]
    delivery:
      webhookUrl:
        secretRef: slack-webhook-url
  secrets:
  - name: slack-webhook-url
    value: projects/262530383813/secrets/slack-webhook-url-pipeline-dev/versions/1

